apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-deployment
  labels:
    app: shopping
spec:
  replicas:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  
  selector:
    matchLabels:
      app: shopping-frontend
  template:
    metadata:
      labels:
        app: shopping-frontend
    spec:
      containers:
        - name: cont-1
          image:
          ports:
            - containerPort: 80
      
      resource:
        requests:
          cpu: 25m 
          memory: 25Mi 
        limits:
          cpu: 50m 
          memory: 50Mi 
--- 
apiVersion: v1 
metadata:
  name: frontend-service
  labels:
    app: shopping
spec:
  type: ClusterIP
  selector:
    app: shopping-frontend 
  ports:
    - port: 80
      targePort: 80