apiVersion: v1
kind: ConfigMap
metadata:
  name: shopping-user-configmap
  labels:
    app: shopping
data:
  USER_SERVICE_PORT: "3001"
  USER_DB_PORT: "3306"
  USER_DB_NAME: "userdb"

---
apiVersion: v1
kind: Secret
metadata:
  name: shopping-user-secret
  labels:
    app: shopping
type: Opaque
data:
  USER_DB_HOST: bXlzcWwtdXNlcg==          # mysql-user
  USER_DB_USER: dXNlcl9zZXJ2aWNl          # user_service
  USER_DB_PASSWORD: dXNlcnBhc3MxMjM=      # userpass123

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-user-deployment
  labels:
    app: shopping
spec:
  replicas: 1

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  selector:
    matchLabels:
      app: shopping-user

  template:
    metadata:
      labels:
        app: shopping-user
    spec:
      containers:
        - name: user-service
          image: avinashg0/shopping:user
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 3001

          envFrom:
            - configMapRef:
                name: shopping-user-configmap
            - secretRef:
                name: shopping-user-secret

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi

          readinessProbe:
            httpGet:
              path: /
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 10

          volumeMounts:
            - mountPath: /tmp/user-vol
              name: user-vol

      volumes:
        - name: user-vol
          emptyDir: {}

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: shopping-user-hpa
  labels:
    app: shopping
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shopping-user-deployment

  minReplicas: 1
  maxReplicas: 3

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75

---
apiVersion: v1
kind: Service
metadata:
  name: shopping-user-service
  labels:
    app: shopping
spec:
  type: ClusterIP
  selector:
    app: shopping-user
  ports:
    - port: 80
      targetPort: 3001
