apiVersion: v1
kind: ConfigMap
metadata:
  name: shopping-api-gateway-configmap
  labels:
    app: shopping
data:
  API_GATEWAY_PORT: "3000"
  USER_SERVICE_URL: "http://user-service:3001"
  PRODUCT_SERVICE_URL: "http://product-service:3002"
  ORDER_SERVICE_URL: "http://order-service:3003"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-api-gateway-deployment
  labels:
    app: shopping
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  selector:
    matchLabels:
      app: shopping-api-gateway

  template:
    metadata:
      labels:
        app: shopping-api-gateway
    spec:
      containers:
        - name: api-gateway
          image: avinashg0/shopping:api-gateway-${API_GATEWAY_VERSION}
          ports:
            - containerPort: 3000

          resources:
            requests:
              cpu: 25m
              memory: 25Mi
            limits:
              cpu: 50m
              memory: 50Mi

          envFrom:
            - configMapRef:
                name: shopping-api-gateway-configmap

          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          
          volumeMount:
            mountPath: /tmp/api-gateway-vol
            name: api-gateway-vol
      volume:
        name: api-gateway-vol
        emptyDir: {}

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: shopping-api-gateway-hpa
  labels:
    app: shopping
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shopping-api-gateway-deployment

  minReplicas: 1
  maxReplicas: 2

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80

---
apiVersion: v1
kind: Service
metadata:
  name: shopping-api-gateway-service
  labels:
    app: shopping
spec:
  type: ClusterIP
  selector:
    app: shopping-api-gateway
  ports:
    - port: 80
      targetPort: 3000
