apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-configmap
  namespace: shopping
data:
  API_GATEWAY_PORT: "3000"
  USER_SERVICE_URL: "http://user-service:80"
  PRODUCT_SERVICE_URL: "http://product-service:80"
  ORDER_SERVICE_URL: "http://order-service:80"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-configmap
  namespace: shopping
data:
  USER_SERVICE_PORT: "3001"
  USER_DB_PORT: "3306"
  USER_DB_NAME: "userdb"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: product-configmap
  namespace: shopping
data:
  PRODUCT_SERVICE_PORT: "3002"
  PRODUCT_DB_NAME: "productdb"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: order-configmap
  namespace: shopping
data:
  ORDER_SERVICE_PORT: "3003"
  ORDER_DB_NAME: "orderdb"